CREATE TABLE ALUNO (
    CODIGOALUNO int NOT NULL,
    NOME varchar(90) NOT NULL,
    CPF char(15) NOT NULL,
    SEXO char(1) NOT NULL,
    DTNASCIMENTO date NOT NULL,
    CONSTRAINT ALUNO_pk PRIMARY KEY (CODIGOALUNO)
);