INSERT INTO CLIENTE (CODIGOCLIENTE, NOME, CPF, SEXO)
VALUES (1, 'ROBERTA SILVA BRASIL', '82998', 'F');
INSERT INTO CLIENTE (CODIGOCLIENTE, NOME, CPF, SEXO)
VALUES (2, 'MARCOS PEREIRA BRASIL', '9999', 'M');
INSERT INTO CLIENTE (CODIGOCLIENTE, NOME, CPF, SEXO)
VALUES (3, 'HEMERSON SILVA BRASIL', '9111', 'M');
/*or*/
INSERT INTO CLIENTE (CODIGOCLIENTE, NOME, CPF, SEXO)
VALUES (1, 'ROBERTA SILVA BRASIL', '82998', 'F'),
    (2, 'MARCOS PEREIRA BRASIL', '9999', 'M'),
(3, 'HEMERSON SILVA BRASIL', '9111', 'M');