/*UNION*/
SELECT NOME,
    CPF
FROM FUNCIONARIO
UNION
SELECT NOME,
    CPF
FROM CLIENTE;
/*UNION ALL*/
SELECT NOME,
    CPF,
    'Dados da tabela FUNCIONARIO' AS ORIGEM
FROM FUNCIONARIO
UNION ALL
SELECT NOME,
    CPF,
    'Dados da tabela CLIENTE' AS ORIGEM
FROM CLIENTE;
/*INTERSECT*/
SELECT NOME,
    CPF
FROM FUNCIONARIO
INTERSECT
SELECT NOME,
    CPF
FROM CLIENTE;
/*UNION-INTERSECT*/
SELECT NOME,
    CPF
FROM FUNCIONARIO
UNION
SELECT NOME,
    CPF
FROM CLIENTE
INTERSECT
SELECT NOME,
    CPF
FROM ALUNO;
/*EXCEPT*/
SELECT NOME,
    CPF
FROM FUNCIONARIO
EXCEPT
SELECT NOME,
    CPF
FROM CLIENTE;
/*ALIAS*/
SELECT CODIGOALUNO AS "Matrícula",
    NOME AS "Nome do discente",
    DTNASCIMENTO AS "Data de nascimento"
FROM ALUNO;