INSERT INTO DEPARTAMENTO(CODIGODEPARTAMENTO, NOME)
VALUES (1, 'Tecnologia da Informação');
INSERT INTO DEPARTAMENTO(CODIGODEPARTAMENTO, NOME)
VALUES (2, 'Contabilidade');
INSERT INTO DEPARTAMENTO(CODIGODEPARTAMENTO, NOME)
VALUES (3, 'Marketing');
/*or*/
INSERT INTO DEPARTAMENTO(CODIGODEPARTAMENTO, NOME)
VALUES (1, 'Tecnologia da Informação'),
    (2, 'Contabilidade'),
    (3, 'Marketing');