/*RETORNA O CODIGOFUNCIONARIO, NOME DA TABELA FUNCIONARIO ONDE O SALÁRIO FOR IGUAL AO VALOR DO MAIOR SALÁRIO*/
SELECT CODIGOFUNCIONARIO,
    NOME
FROM FUNCIONARIO
WHERE SALARIO = (
        SELECT MAX(SALARIO)
        FROM FUNCIONARIO
    );
/*RETORNA A QUANTIDADE DE FUNCIONARIOS QUE RECEBEM VALOR MENOR QUE O MAIOR SALÁRIO DE UMA FUNCIONÁRIA*/
SELECT COUNT(*) AS QUANTIDADE
FROM FUNCIONARIO
WHERE SALARIO < (
        SELECT MAX(SALARIO)
        FROM FUNCIONARIO
        WHERE SEXO = 'F'
    );