/*RETORNA O CODIGOFUNCIONARIO, NOME DA TABELA FUNCIONARIO ONDE O SALÁRIO FOR IGUAL AO VALOR DO MAIOR SALÁRIO*/
SELECT CODIGOFUNCIONARIO,
    NOME
FROM FUNCIONARIO
WHERE SALARIO = (
        SELECT MAX(SALARIO)
        FROM FUNCIONARIO
    );
/*RETORNA A QUANTIDADE DE FUNCIONARIOS QUE RECEBEM VALOR MENOR QUE O MAIOR SALÁRIO DE UMA FUNCIONÁRIA*/
SELECT COUNT(*) AS QUANTIDADE
FROM FUNCIONARIO
WHERE SALARIO < (
        SELECT MAX(SALARIO)
        FROM FUNCIONARIO
        WHERE SEXO = 'F'
    );
/*DIVERSOS*/
SELECT CODIGOFUNCIONARIO,
    NOME,
    SALARIO
FROM FUNCIONARIO F
    JOIN (
        SELECT CODIGODEPARTAMENTO,
            AVG(SALARIO) AS MEDIA
        FROM FUNCIONARIO
        GROUP BY CODIGODEPARTAMENTO
    ) TESTE ON F.CODIGODEPARTAMENTO = TESTE.CODIGODEPARTAMENTO
WHERE SALARIO > MEDIA;

/*DIVERSOS*/
UPDATE FUNCIONARIO F
SET SALARIO = (
        SELECT MAX(SALARIO)
        FROM FUNCIONARIO
        WHERE CODIGODEPARTAMENTO = F.CODIGODEPARTAMENTO
    )
WHERE F.CODIGODEPARTAMENTO IS NOT NULL;
SELECT D.CODIGODEPARTAMENTO,
    D.NOME
FROM DEPARTAMENTO D
WHERE EXISTS (
        SELECT F.CODIGODEPARTAMENTO
        FROM FUNCIONARIO F
        WHERE D.CODIGODEPARTAMENTO = F.CODIGODEPARTAMENTO
    );
/*DIVERSOS*/
SELECT D.CODIGODEPARTAMENTO,
    D.NOME
FROM DEPARTAMENTO D
WHERE NOT EXISTS (
        SELECT F.CODIGODEPARTAMENTO
        FROM FUNCIONARIO F
        WHERE D.CODIGODEPARTAMENTO = F.CODIGODEPARTAMENTO
    );